### ISSUE TITLE
notificationsJSONForApplication only works for stock apps

### ISSUE THREAD

**Issue by GaitherStephens** [Matchstic/InfoStats2#3] opened 2016-12-04 15:31 UTC
Stock apps such as [IS2Notifications notificationsJSONForApplication:@"" + "com.apple.mobilemail"] works fine but when using "com.facebook.Facebook" or other 3rd party bundleID's the array fails to populate.

**Comment by Matchstic** [comment] 2016-12-12 17:24
It appears an exception is being thrown in my code to convert notifications to JSON format; requesting the BBBulletin objects directly in notificationsForApplication: works as expected.

**Comment by Matchstic** [comment] 2016-12-12 17:36
I've now confirmed why this isn't working for non-stock apps. It turns out, the title field for the notification will be nil if from a non-stock app; typically, this is replaced by the application's name on SpringBoard instead. That then trips up my code for escaping a string for use in JSON, leading to nil output.

**Comment by Matchstic** [comment] 2016-12-12 17:47
Fixed as of commit https://github.com/Matchstic/InfoStats2/commit/c61483fa948748aa7257b09a272e905f3cbffb00

Here's a deb to test with; please can you confirm it's now resolved your end too? https://www.dropbox.com/s/64zwegvk8pxbpmd/com.matchstic.InfoStats2_1.0.1-10_iphoneos-arm.deb?dl=0

**Comment by GaitherStephens** [comment] 2016-12-17 22:49
Works great.

**Closed as completed** 2017-01-20 17:13 UTC
Labels: bug
